---
- hosts: all
  become: true
  tasks: 

  - name: update repository index
    tags: apache,ubuntu
    ansible.builtin.apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"   

  - name: remove apache2 package
    tags: apache,ubuntu
    ansible.builtin.apt:
      name: apache2
      state: absent
    when: ansible_distribution == "Ubuntu"  
    
  - name: remove support for php
    tags: apache,ubuntu
    ansible.builtin.apt:
      name: libapache2-mod-php
      state: absent
    when: ansible_distribution == "Ubuntu"  
    
  - name: remove apache on web server (fedora)
    tags: apache,fedora
    ansible.builtin.dnf:
      name: httpd
      state: absent
    when: ansible_distribution == "Fedora"
