- name: Manage windows servers
  hosts: Windows_Servers
  tasks:
    - name: Create directory structure
      win_file:
        path: c:\Temp\folder
        state: directory

    - name: Touch a file (creates id note present, updates notification time if present)
      win_file:
        path: c:\Temp\folder\foo.txt
        state: touch

    - name: Create a file from a Jinja2 template
      win_template:
        src: foo.txt.j2
        dest: c:\temp\folder\foo.txt
    - win_stat:
        path: c:\temp\folder\foo.txt
        get_checksum: yes
        checksum_algorithm: md5
      register: md5_checksum

    - debug:
        var: md5_checksum.stat.checksum

    - name: Create local group to contain new users
      win_group:
        name: LocalGroup
        description: Allow access to C:\Development folder

    - name: Create local users
      win_user:
        name: Harold
        password: Bananas4321!
        groups: LocalGroup
        update_password: on_create
        password_never_expires: true
      win_user:
        name: Jenna
        password: Strawberry4322!
        groups: LocalGroup
        update_password: on_create
        password_never_expires: true
      win_user:
        name: Cori
        password: Pineapple4321!
        groups: LocalGroup
        update_password: on_create
        password_never_expires: true
              
    - name: Create Development folder
      win_file:
        path: C:\Development
        state: directory

    - name: Set ACL of Development folder
      win_acl:
        path: C:\Development
        rights: FullControl
        state: present
        type: allow
        user: LocalGroup

    - name: Remove parent inheritance of Development folder
      win_acl_inheritance:
        path: C:\Development
        reorganize: true
        state: absent    

    - name: Run an executable using win_command
      win_command: whoami.exe    

    - name: Install all security updates
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
    
    #- name: Reboot host if required
     # win_reboot:
      #when: update_result.reboot_required
    
    

    
